services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shiori
      POSTGRES_USER: shiori
      POSTGRES_PASSWORD: shioritemppass
    ports:
      - "5332:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shiori -d shiori"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db: